### ISSUE TITLE
BattleBlobs Title Image Missing

### ISSUE THREAD

**Issue by keraion** [Foony-Limited/foony-issues#2]
The title image for BattleBlobs is missing
https://foony.com/img/games/battleships/title.webp

![image](https://user-images.githubusercontent.com/105471409/191642514-7abdf7a1-a9ff-4602-91ba-359a63b8ab14.png)

![image](https://user-images.githubusercontent.com/105471409/191642379-f7676840-48cd-4660-8e1e-5917d714b464.png)

**Comment by acorn1010** [comment]
Fixed!
